[project]
name = "transformed-ingredients"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pyvolca",
    "sacremoses>=0.1.1",
    "sentencepiece>=0.2.1",
    "torch>=2.11.0",
    "transformers>=5.5.3",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "sentence-transformers>=5.1.2",
    "pronto>=2.7.2",
]

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true  # only match packages that request this index explicitly (torch)
