[project]
name = "document-ia-api"
version = "1.0.8"
description = "API minimaliste FastAPI avec authentification API_KEY"
authors = [{name = "Romaric HALDENWANG",email = "romaric.haldenwang@beta.gouv.fr"}, {name = "Nicolas Sagon",email = "nicolas.sagon@beta.gouv.fr"}]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi == 0.136.3",
    "starlette == 1.0.1",
    "python-dotenv == 1.2.2",
    "pydantic-settings == 2.14.1",
    "sqlalchemy == 2.0.50",
    "uvicorn == 0.24.0.post1",
    "gunicorn == 22.0.0",
    "python-magic == 0.4.27",
    "python-multipart == 0.0.6",
    "asyncpg == 0.30.0",
    "greenlet == 3.5.1",
    "alembic == 1.18.4",
    "psycopg2-binary == 2.9.12",
    "document-ia-infra",
    "document-ia-schemas",
    "python-logging-loki == 0.3.1",
    "argon2-cffi == 25.1.0",
    "cryptography == 43.0.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff == 0.12.12",
    "pytest == 8.4.2",
    "pytest-asyncio == 0.23.8",
    "pre-commit == 3.8.0",
    "httpx == 0.27.2",
    "pyright == 1.1.409",
    "boto3-stubs == 1.43.16",
]

[tool.uv]
exclude-newer = "2 days"

[tool.uv.sources.document-ia-infra]
path = "../document-ia-infra"
editable = true

[tool.uv.sources.document-ia-schemas]
path = "../document-ia-schemas"
editable = true

[tool.hatch.build.targets.wheel]
packages = ["src/document_ia_api"]

[tool.ruff]
target-version = "py313"
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.pytest.ini_options]
asyncio_mode = "auto"
