[project]
name = "document-ia-worker"
version = "1.0.8"
description = "Worker document ia"
authors = [{name = "Nicolas Sagon",email = "nicolas.sagon@beta.gouv.fr"}]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "document-ia-infra",
    "document-ia-schemas",
    "python-dotenv == 1.2.2",
    "pydantic-settings == 2.14.1",
    "pytesseract == 0.3.13",
    "pymupdf == 1.27.2.3",
    "opencv-python-headless == 4.13.0.92",
    "jinja2 == 3.1.6",
    "pydantic == 2.13.4",
    "mypy-boto3-s3 == 1.43.14",
    "greenlet == 3.5.1",
    "zxing-cpp == 2.3.0",
    "2ddoc-parser",
    "python-magic == 0.4.27",
    "psycopg2-binary == 2.9.12",
    "torch == 2.7.1+cpu; sys_platform == 'linux'",
    "torch == 2.7.1; sys_platform == 'darwin'",
    "torchvision == 0.22.1+cpu; sys_platform == 'linux'",
    "torchvision == 0.22.1; sys_platform == 'darwin'",
    "qrdet == 2.5",
    "pyright == 1.1.409",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff == 0.12.12",
    "pytest == 8.4.2",
    "pytest-asyncio == 0.23.8",
    "pre-commit == 3.8.0",
    "uvicorn == 0.38.0",
]

[tool.uv]
exclude-newer = "2 days"

[tool.uv.sources.document-ia-infra]
path = "../document-ia-infra"
editable = true

[tool.uv.sources.document-ia-schemas]
path = "../document-ia-schemas"
editable = true

[tool.uv.sources.2ddoc-parser]
git = "https://github.com/betagouv/2ddoc-parser.git"
tag = "v1.0.5"

[[tool.uv.sources.torch]]
index = "pytorch-cpu"
marker = "sys_platform == 'linux'"

[[tool.uv.sources.torchvision]]
index = "pytorch-cpu"
marker = "sys_platform == 'linux'"

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.hatch.build.targets.wheel]
packages = ["src/document_ia_worker", "src/document_ia_task_scheduler"]

[tool.ruff]
target-version = "py313"
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.pytest.ini_options]
asyncio_mode = "auto"
