services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123" 
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_PASSWORD: ${DWH_PASSWORD}
      CLICKHOUSE_USER: ${DWH_USERNAME}
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data: