# Cette image est utilisée pour les étapes de build des autres services (server, worker-sync, worker-file)
# afin d'éviter de dupliquer les étapes de build communes (installation des dépendances, etc.) et ainsi accélérer le temps de build global.
x-server-image: &server_image
  image: biblio-num/server-runtime:prod
  build:
    target: production
    context: ../../
    dockerfile: ./apps/server/Dockerfile
  platform: linux/amd64
  networks:
    - biblio-num-network
  depends_on:
    - db
  env_file:
    - .env.docker

services:
  bn-http-proxy:
    profiles:
      - prod
    build:
      context: ../../
      dockerfile: ./apps/http-proxy/Dockerfile
    container_name: biblio-num_http-proxy
    depends_on:
      - client
      - server
    image: biblio-num/http-proxy
    platform: linux/amd64
    ports:
      - "${DC_BN_HTTP_PROXY_PORT:-8088}:8088"
    networks:
      - biblio-num-network

  client:
    profiles:
      - prod
    build:
      target: production
      context: ../../
      dockerfile: ./apps/client/Dockerfile
      args:
        - VITE_APP_OPEN_SOURCE=${VITE_APP_OPEN_SOURCE:-false}
    image: biblio-num/client:prod
    platform: linux/amd64
    container_name: biblio-num_client
    ports:
      - "${DC_CLIENT_PORT:-8080}:8080"
    networks:
      - biblio-num-network
    env_file: # À injecter les variables dans le container au runtime.
      - .env.docker

  server:
    profiles:
      - prod
    <<: *server_image
    container_name: biblio-num_server
    ports:
      - "${DC_API_PORT:-3000}:3000"

  worker-sync:
    profiles:
      - prod
    <<: *server_image
    container_name: biblio-num_worker_sync
    command: pnpm run start:worker-sync:prod

  worker-file:
    profiles:
      - prod
    <<: *server_image
    container_name: biblio-num_worker_file
    command: pnpm run start:worker-file:prod

  db:
    profiles:
      - prod
      - simple-dev
      - db-only
      - ci
    image: postgres:18.3 #Attention la version mineur de la prod n'est pas fixer
    container_name: biblio-num_db
    environment:
      POSTGRES_DB: biblio-num
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 2s
      timeout: 2s
      retries: 10
    ports:
      - "${DC_POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - type: volume
        source: biblio-num-db-volume
        target: /var/lib/postgresql/data
    networks:
      - biblio-num-network

  adminer:
    profiles:
      - adminer
      - prod
    image: adminer
    ports:
      - "${DC_ADMINER_PORT:-8010}:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DEFAULT_SYSTEM=PostgreSQL
      - ADMINER_DESIGN=lucas-sandery
    networks:
      - biblio-num-network

  pgadmin:
    profiles:
      - pgadmin
    image: dpage/pgadmin4
    container_name: biblio-num_dbadmin
    depends_on:
      - db
    ports:
      - "${DC_PGADMIN_PORT:-3020}:80"
    volumes:
      - type: volume
        source: biblio-num-pgadmin-volume
        target: /var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - biblio-num-network

  mailhog:
    profiles:
      - prod
      - simple-dev
      - tests-e2e
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "${SMTP_PORT:-1025}:1025"
      - "${DC_MAILHOG_WEB_PORT:-8025}:8025"
    networks:
      - biblio-num-network

  s3:
    profiles:
      - prod
      - simple-dev
      - tests-e2e
      - s3-only
    image: quay.io/minio/minio:RELEASE.2023-01-20T02-05-44Z
    container_name: biblio-num_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin} # MINIO_ACCESS_KEY = MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password} # MINIO_SECRET_KEY = MINIO_ROOT_PASSWORD
    volumes:
      - type: volume
        source: biblio-num-s3-volume
        target: /data
    command: server --address ":9000" --console-address ":9001" /data
    ports:
      - "${DC_MINIO_PORT:-9000}:9000"
      - "${DC_MINIO_CONSOLE_PORT:-9001}:9001"
    networks:
      - biblio-num-network

  s3-init:
    profiles:
      - prod
      - simple-dev
      - tests-e2e
      - s3-only
    image: minio/mc:RELEASE.2024-01-13T08-44-48Z
    depends_on:
      - s3
    networks:
      - biblio-num-network
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://s3:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD; do
        echo 'waiting for minio...'; sleep 2;
      done;
      mc mb -p local/$$AWS_DEFAULT_S3_BUCKET || true;
      echo 'Bucket $$AWS_DEFAULT_S3_BUCKET created or already exists';
      mc admin user add local $$ACCESS_KEY_ID $$SECRET_ACCESS_KEY || true;
      echo 'User $$ACCESS_KEY_ID created or already exists';
      mc admin policy attach local readwrite --user $$ACCESS_KEY_ID;
      echo 'MinIO init done';
      "
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password}
      AWS_DEFAULT_S3_BUCKET: ${AWS_DEFAULT_S3_BUCKET:-super-bucket}
      ACCESS_KEY_ID: ${ACCESS_KEY_ID:-bn-access}
      SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY:-bn-secret-please-change}


  redis:
    profiles:
      - prod
      - simple-dev
      - ci
    image: docker.io/redis:8.2.1
    platform: linux/amd64
    container_name: redis
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - biblio-num-network

  bullboard:
    profiles:
      - prod
      - simple-dev
    container_name: bullboard
    image: deadly0/bull-board
    ports:
      - "${DC_BULLBOARD_PORT:-3010}:3000"
    networks:
      - biblio-num-network
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
      BULL_PREFIX: bull
      USER_LOGIN: admin
      USER_PASSWORD: password
      REDIS_DB: "${REDIS_INDEX:-0}"
    depends_on:
      - redis

networks:
  biblio-num-network:
    name: biblio-num-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  biblio-num-pgadmin-volume:
  biblio-num-s3-volume:
  biblio-num-db-volume:
  biblio-num-server-node_modules-volume:
  biblio-num-worker-node_modules-volume:
