[project]
name = "depenses-eclairees"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.13"
dependencies = [
    # Doc analyze
    "docx2txt",
    "python-dotenv",
    "olefile",  # File type identification for old Microsoft Office files (.xls, .doc, ...)
    "openai",
    "openpyxl",  # pandas xlsx read
    "pandas",
    "Pillow",
    "PyMuPDF",
    "python-magic",  # File type identification
    "tiktoken",
    "tqdm",
    "tesserocr (>=2.9.1,<3.0.0)",
    "unidecode (>=1.4.0,<2.0.0)",  # File name cleaning
    "xlrd",  # pandas xls read
    "schwifty (>=2026.1.0,<2027.0.0)",
    "tabulate (>=0.10.0,<0.11.0)",  # pandas to_markdown
    "odfpy (>=1.4.1,<2.0.0)",  # pandas ods read
    "pyxlsb (>=1.0.10,<2.0.0)",  # pandas xlsb read

    # Django
    "Django~=5.2",
    "psycopg[binary]",
    "djangorestframework~=3.16",
    "celery[redis] (>=5.5.3,<6.0.0)",
    "django-environ (>=0.12.0,<0.13.0)",
    "whitenoise (>=6.11.0,<7.0.0)",
    "django-celery-results (>=2.6.0,<3.0.0)",
    "gunicorn (>=23.0.0,<24.0.0)",
    "django-dsfr (>=3.2.0,<4.0.0)",
    "mozilla-django-oidc (>=4.0.1,<5.0.0)",
    "django-lasuite (>=0.0.23,<0.1.0)",
    "django-storages[s3] (>=1.14.6,<2.0.0)",
    "moto (>=5.1.20,<6.0.0)",
    "ipython (>=9.13.0,<10.0.0)",
]

[tool.poetry]
package-mode = false

[dependency-groups]
dev = [
    "freezegun",
    "pytest",
    "xlwt",
    "pytest-cov",
    "pytest-django",
    "pytest-factoryboy",
    "pytest-responses",
    "pytest-ruff",
    "ruff",

    # stubs
    "pandas-stubs",
    "celery-types (>=0.26.0,<0.27.0)",
    "django-stubs (>=6.0.3,<7.0.0)",
]


[tool.ruff]
line-length = 120
exclude = [
    "**/migrations/*.py",
]

[tool.ruff.lint]
select = [
    "I",  # isort
    "F",  # pyflakes
    "E",  # pycodestyle
    "DJ",  # flake8-django
]

[tool.ruff.lint.isort]
section-order = [
    "future",
    "standard-library",
    "django",
    "third-party",
    "pandas",
    "first-party",
    "local-folder",
]

[tool.ruff.lint.isort.sections]
# Group all Django and Pandas imports into a separate section.
django = ["django"]
pandas = ["pandas", "numpy"]

[tool.ruff.lint.per-file-ignores]
# Ignore line too long in attributes definitions
"docia/file_processing/processor/attributes/**.py" = ["E501"]



[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "docia.settings"


[tool.coverage.run]
branch = true
omit = [
    # omit migrations
    "*/migrations/*",
]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain about missing debug-only code:
    "if self\\.debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
    ]
